### ISSUE TITLE
Topic list does not follow standard AsciiBinder, leading to strange navigation menus

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-documentation#97]
Because of the way the docs are structured, the left side nav becomes unusable.

An example of what I'd expect is present in the REST API docs, where clicking the specific item brings you to documentation for just that piece:

<img width="291" alt="manageiq nightly build manageiq documentation welcome 2016-09-02 14-35-10" src="https://cloud.githubusercontent.com/assets/52120/18214364/b1720a86-711a-11e6-9e0d-eeb90026c44d.png">

However, the docs that were transferred from CloudForms are in the following format, where clicking the "Index" brings you to giant page that has everything, including an embedded Table Of Contents.

<img width="298" alt="manageiq nightly build installing manageiq on google compute engine table of contents index 2016-09-02 14-35-43" src="https://cloud.githubusercontent.com/assets/52120/18214384/d58f2872-711a-11e6-90ea-d251665359b2.png">

---

I tried tweaking this myself, but the structure confuses me at the moment and I'm concerned I'm breaking something for CloudForms, which I can't test the build against.  For example, the index file actually includes the topics files via a `numbered:` directive.  I tried changing the _distro_map.yml to directly point to the topics files, bypassing the index file, but then I get some pathing errors because I think AsciiBinder can't handle that unexpected structure.  I even tried tweaking AsciiBinder to deal with it, but then things like images are not referenced correctly.

cc @adahms 
If you need more information, let's discuss.  I have an idea for the structure of the repo, but I don't understand the limitations because of the downstream build.

**Comment by hayesr** [comment]
Revisiting this issue now that we are trying to support multiple branches of the docs on the website. For the time being we'll custom menus, but that might not scale well. It would be preferable to organize things here instead so we can fully automate the doc builds.

**Comment by adahms** [comment]
@Fryguy @hayesr Thank you for adding me to this thread, and I think this is a really good question. I do have a few ideas about how we can simply the current structure so that we can get rid of the need to differentiate between 'cfme' and 'miq' in the same repository, which would help on that front, but the question of topics is a larger one that I would be keen to explore.

Based on my understanding, AsciiBinder expects topics to be laid out so that each chapter has its own directory, and then for those directories to be referenced via the topic map. While I can see the benefit from this, I am a little worried about the potential overhead of having to ensure all files are arranged this way, so I'm curious to hear a little bit more about requirements and whether this process can be automated somehow.

That said, I am open to seeing how we can improve this structure, so let me know if you have any questions or concerns, and I'll do some research.

**Comment by chessbyte** [comment]
No longer an issue since the documentation has been converted to Markdown.
